Improve codebase and add Laravel support
Merkeleon/php-cryptocurrency-address-validation pull request #26
Opened 2023-04-24 10:45 UTC by LiquidCats

2023-05-12 11:59 UTC, androzd requested changes

2023-05-12 11:59 UTC, androzd commented on config/address_validation.php
> +    ],
binance = ethereum

2023-05-12 11:59 UTC, androzd commented on config/address_validation.php
> +            ['tb' => null]
['tb' => null, 'bcrt' => null]

2023-05-12 11:59 UTC, androzd commented on config/address_validation.php
> +    ],
ethereum_classic = ethereum

2023-05-12 11:59 UTC, androzd commented on config/address_validation.php
> +        )
testnet:
['tltc' => null, 'rltc' => null]

2023-05-12 11:59 UTC, androzd commented on src/Drivers/DefaultBase58Driver.php
> +        return hexdec($addressVersion) === hexdec($calculatedAddressVersion);
А почему два hexdec сравниваем?

2023-05-12 11:59 UTC, androzd commented on src/Drivers/KeccakDriver.php
> +class KeccakDriver extends AbstractDriver
Может стоит сделать для KeccakDriver какой-то параметр strict, на проверку ckecksum формата, либо если его не передали, проверять регуляркой, без соблюдения формата.
Либо разделить на два драйвера (KeccakDriver / KeccakStrictDriver)

2023-05-12 11:59 UTC, androzd commented on tests/ValidatorTest.php
> +            'Ethereum #2' => [CurrencyEnum::ETHEREUM, 'testnet', true, '0x799aD3Ff7Ef43DfD1473F9b8a8C4237c22D8113F'],
Было бы неплохо проверить в нижнем регистре адреса, с разделением на KeccakDriver / KeccakChecksumDriver

2023-05-17 13:17 UTC, LiquidCats commented on src/Drivers/DefaultBase58Driver.php
> +        return hexdec($addressVersion) === hexdec($calculatedAddressVersion);
я могу ошибать, но мне попадался кейс когда hex могли быть разными но иметь один decimal

2023-06-13 11:37 UTC, merged